name = "vany"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Routes - TUI serving and protocol info pages
routes = [
  { pattern = "start.vany.sh", custom_domain = true },
  { pattern = "mtp.vany.sh", custom_domain = true },
  { pattern = "reality.vany.sh", custom_domain = true },
  { pattern = "wg.vany.sh", custom_domain = true },
  { pattern = "vray.vany.sh", custom_domain = true },
  { pattern = "ws.vany.sh", custom_domain = true },
  { pattern = "dnstt.vany.sh", custom_domain = true },
  { pattern = "conduit.vany.sh", custom_domain = true },
  { pattern = "vany.sh", custom_domain = true }
]
